/* ============================================================
   Streams — the two "AI is writing" demos.
   1. IDE stream: pretokenized source code revealed char-by-char.
   2. AI chat stream: a fake reasoning response revealed word-by-word
      with a thinking-pill label that flips through fake stages.
   ============================================================ */

// ---------- IDE token stream ----------

const IDE_PROGRAM = [
  { c: "// generated by synthetica · push to merge\n", cls: "tok-com" },
  { c: "export async function ", cls: "tok-key" },
  { c: "POST", cls: "tok-fn" },
  { c: "(req: Request) {\n", cls: "" },
  { c: "  const ", cls: "tok-key" },
  { c: "{ prompt, userId } ", cls: "" },
  { c: "= ", cls: "tok-key" },
  { c: "await req.", cls: "" },
  { c: "json", cls: "tok-fn" },
  { c: "();\n", cls: "" },
  { c: "  const ", cls: "tok-key" },
  { c: "ctx ", cls: "" },
  { c: "= ", cls: "tok-key" },
  { c: "await ", cls: "tok-key" },
  { c: "retrieve", cls: "tok-fn" },
  { c: "(prompt, ", cls: "" },
  { c: "{ topK: ", cls: "" },
  { c: "12", cls: "tok-num" },
  { c: " });\n", cls: "" },
  { c: "  return ", cls: "tok-key" },
  { c: "stream", cls: "tok-fn" },
  { c: "({ ", cls: "" },
  { c: "model: ", cls: "" },
  { c: "\"claude-opus-4-7\"", cls: "tok-str" },
  { c: ", prompt, ctx });\n", cls: "" },
  { c: "}\n", cls: "" },
];

export function mountIdeStream(el) {
  let i = 0;
  let charIdx = 0;
  const caret = '<span class="ide-caret"></span>';

  const tick = () => {
    if (i >= IDE_PROGRAM.length) {
      // pause, then loop again
      setTimeout(() => {
        i = 0;
        charIdx = 0;
        el.innerHTML = caret;
        tick();
      }, 3000);
      return;
    }
    const tok = IDE_PROGRAM[i];
    charIdx += 1;
    if (charIdx > tok.c.length) {
      i += 1;
      charIdx = 0;
      tick();
      return;
    }
    let html = "";
    for (let k = 0; k < i; k++) {
      const t = IDE_PROGRAM[k];
      html += t.cls
        ? `<span class="${t.cls}">${escapeHtml(t.c)}</span>`
        : escapeHtml(t.c);
    }
    const partial = tok.c.slice(0, charIdx);
    html += tok.cls
      ? `<span class="${tok.cls}">${escapeHtml(partial)}</span>`
      : escapeHtml(partial);
    html += caret;
    el.innerHTML = html;
    // variable typing speed for "natural" feel
    const ms = 14 + Math.random() * 28 + (partial.endsWith("\n") ? 120 : 0);
    setTimeout(tick, ms);
  };
  tick();
}

// ---------- AI chat stream ----------

const AI_REPLY =
  "Q3 churn is bleeding from your SMB cohort (acquired Apr–Jun '25). " +
  "Net retention there is 71% vs. 104% in mid-market and 118% in enterprise. " +
  "The proximate cause is your onboarding regression — 38% of SMB signups " +
  "now drop before the second-week activation event, up from 12% last quarter. " +
  "I'd recommend a targeted save offer for accounts with usage > 0 in week 1 " +
  "but no team invites. Want me to draft the offer and queue it?";

const THINKING_STAGES = [
  "reasoning…",
  "retrieving context…",
  "querying snowflake…",
  "synthesizing…",
  "drafting…",
];

export function mountAiStream(streamEl, labelEl) {
  let stage = 0;
  const flipStage = setInterval(() => {
    stage = (stage + 1) % THINKING_STAGES.length;
    labelEl.textContent = THINKING_STAGES[stage];
  }, 900);

  const tokens = AI_REPLY.split(/(\s+)/); // keep whitespace tokens
  let i = 0;
  let txt = "";

  const tick = () => {
    if (i >= tokens.length) {
      clearInterval(flipStage);
      labelEl.textContent = "done · 1.3s";
      streamEl.innerHTML = escapeHtml(txt);
      // restart after a beat
      setTimeout(() => {
        i = 0;
        txt = "";
        mountAiStream(streamEl, labelEl);
      }, 6000);
      return;
    }
    txt += tokens[i];
    i += 1;
    streamEl.innerHTML =
      escapeHtml(txt) + '<span class="stream-caret"></span>';
    const ms = 18 + Math.random() * 80;
    setTimeout(tick, ms);
  };
  tick();
}

function escapeHtml(s) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}
