import {
  Sparkle,
  GradientText,
  StatusDot,
  LatencyPing,
  ModelChip,
  TokenBadge,
  ConfidenceMeter,
  SourceGlyph,
  Button,
  StickyBanner,
  EyebrowPill,
  Rotator,
  WordRoll,
  PromptHero,
  Prompt,
  AsciiHero,
  Aurora,
  NodeGraphBackground,
  FloatingSparkles,
  GlassCard,
  MockIDE,
  SecurityTheater,
  MetricStack,
  ScrollNarrative,
  LaunchTimeline,
  AgentRunway,
  ModelLeaderboard,
  ChatBubble,
  TokenStream,
  ChatFAB,
  PromptComposer,
  LogoMarquee,
  LogoRow,
  StatCounter,
  CommunityBadge,
  FomoFeed,
  PricingCard,
  BeforeAfter,
  WaitlistForm,
  type IdeToken,
} from "performative-ui";
import type { ComponentMeta } from "./ComponentPage";

/* ------------------------------------------------------------
   Shared demo helpers (jsdelivr serves simple-icons SVGs CORS-friendly).
   ------------------------------------------------------------ */
const ic = (slug: string) =>
  `https://cdn.jsdelivr.net/npm/simple-icons@11/icons/${slug}.svg`;

const SAMPLE_TOKENS: IdeToken[] = [
  { c: "// generated by synthetica · push to merge\n", cls: "com" },
  { c: "export async function ", cls: "key" },
  { c: "POST", cls: "fn" },
  { c: "(req: Request) {\n" },
  { c: "  const ", cls: "key" },
  { c: "{ prompt, userId } " },
  { c: "= ", cls: "key" },
  { c: "await req." },
  { c: "json", cls: "fn" },
  { c: "();\n" },
  { c: "  return ", cls: "key" },
  { c: "stream", cls: "fn" },
  { c: "({ model: " },
  { c: '"claude-opus-4-7"', cls: "str" },
  { c: ", prompt });\n" },
  { c: "}\n" },
];

/* ------------------------------------------------------------
   The catalog. Each entry powers a docs page.
   ------------------------------------------------------------ */
export const COMPONENTS: ComponentMeta[] = [
  /* ============================ ATOMS ============================ */
  {
    slug: "sparkle",
    category: "Atoms",
    name: "Sparkle",
    snark: "Add ✦ to any noun to ship it twice as fast.",
    sources: [
      { name: "v0.app", url: "https://v0.app" },
      { name: "lovable.dev", url: "https://lovable.dev" },
      { name: "notion.com/product/ai", url: "https://www.notion.com/product/ai" },
    ],
    extra: 412,
    description:
      "The mandatory four-pointed star. Defaults to a twinkling gradient glyph. Pass `solid` for a monochrome variant; pass `static` to stop the twinkle.",
    examples: [
      {
        title: "Default",
        Demo: () => (
          <span style={{ fontSize: 32 }}>
            Generate <Sparkle />
          </span>
        ),
        code: `<Sparkle />`,
      },
      {
        title: "Solid (no gradient)",
        Demo: () => (
          <span style={{ fontSize: 32, color: "#fbbf24" }}>
            <Sparkle solid /> Pro
          </span>
        ),
        code: `<Sparkle solid />`,
      },
      {
        title: "Custom glyph",
        Demo: () => (
          <span style={{ fontSize: 32 }}>
            <Sparkle glyph="❖" /> Magic
          </span>
        ),
        code: `<Sparkle glyph="❖" />`,
      },
    ],
    props: [
      { name: "glyph", type: "string", default: '"✦"', desc: "The character to render." },
      { name: "solid", type: "boolean", desc: "Skip gradient; render in currentColor." },
      { name: "static", type: "boolean", desc: "Disable the twinkle animation." },
    ],
  },

  {
    slug: "gradient-text",
    category: "Atoms",
    name: "GradientText",
    snark: "When italic isn't billion-dollar enough.",
    sources: [
      { name: "linear.app", url: "https://linear.app" },
      { name: "mistral.ai", url: "https://mistral.ai" },
      { name: "vercel.com", url: "https://vercel.com" },
    ],
    extra: 280,
    description:
      "Text painted with the consensus AI gradient. Use `as` to wrap any element. Set `static` to keep it gradient-colored but stop the shift animation.",
    examples: [
      {
        title: "Inline emphasis",
        Demo: () => (
          <h2 style={{ fontSize: 36, margin: 0 }}>
            Built for <GradientText>velocity</GradientText>.
          </h2>
        ),
        code: `<h2>Built for <GradientText>velocity</GradientText>.</h2>`,
      },
      {
        title: "As an h1",
        Demo: () => (
          <GradientText as="h1" style={{ fontSize: 48, margin: 0 }}>
            Infinite possibility
          </GradientText>
        ),
        code: `<GradientText as="h1">Infinite possibility</GradientText>`,
      },
    ],
    props: [
      { name: "as", type: "ElementType", default: "'span'", desc: "Tag to render." },
      { name: "static", type: "boolean", desc: "Disable the gradient shift animation." },
    ],
  },

  {
    slug: "status-dot",
    category: "Atoms",
    name: "StatusDot",
    snark: "Always green, even when it's not.",
    sources: [
      { name: "vercel.com", url: "https://vercel.com" },
      { name: "cursor.com", url: "https://cursor.com" },
      { name: "linear.app", url: "https://linear.app" },
    ],
    extra: 600,
    description:
      "A pulsing colored dot, the universal 'we're live' indicator. Drop into pills, navs, statuses.",
    examples: [
      {
        title: "Default green",
        Demo: () => (
          <span style={{ display: "inline-flex", gap: 8, alignItems: "center", fontSize: 14 }}>
            <StatusDot /> All systems normal
          </span>
        ),
        code: `<StatusDot /> All systems normal`,
      },
      {
        title: "Warn (custom color)",
        Demo: () => (
          <span style={{ display: "inline-flex", gap: 8, alignItems: "center", fontSize: 14 }}>
            <StatusDot color="#fbbf24" /> Degraded performance
          </span>
        ),
        code: `<StatusDot color="#fbbf24" /> Degraded performance`,
      },
    ],
    props: [
      { name: "color", type: "string", default: "var(--pui-success)", desc: "CSS color." },
      { name: "static", type: "boolean", desc: "Disable the pulse." },
    ],
  },

  {
    slug: "latency-ping",
    category: "Atoms",
    name: "LatencyPing",
    isNew: true,
    snark: "A tiny dot for pretending 18ms was inevitable.",
    sources: [
      { name: "vercel.com", url: "https://vercel.com" },
      { name: "linear.app", url: "https://linear.app" },
      { name: "fly.io", url: "https://fly.io" },
    ],
    description:
      "Tiny animated latency/readiness indicator for compact pills, leaderboards, and status rows. Use the visible label for latency text, or `dotLabel` when the indicator is icon-only.",
    examples: [
      {
        title: "Latency row",
        Demo: () => (
          <div style={{ display: "flex", gap: 16, alignItems: "center", flexWrap: "wrap" }}>
            <LatencyPing label="18ms" tone="good" />
            <LatencyPing label="queued" tone="warn" />
            <LatencyPing label="cold" tone="danger" />
            <LatencyPing label="warm" tone="neutral" pulse={false} />
          </div>
        ),
        code: `<LatencyPing label="18ms" tone="good" />
<LatencyPing label="queued" tone="warn" />
<LatencyPing label="cold" tone="danger" />
<LatencyPing label="warm" tone="neutral" pulse={false} />`,
      },
      {
        title: "Icon-only",
        Demo: () => <LatencyPing tone="warn" dotLabel="Queued request" />,
        code: `<LatencyPing tone="warn" dotLabel="Queued request" />`,
      },
    ],
    props: [
      { name: "label", type: "ReactNode", desc: "Visible latency/readiness text." },
      { name: "tone", type: '"good" | "warn" | "danger" | "neutral"', default: '"neutral"', desc: "Signal color tone." },
      { name: "pulse", type: "boolean", default: "true", desc: "Animate the signal ring." },
      { name: "dotLabel", type: "string", desc: "Accessible label when no visible label is provided." },
    ],
  },

  {
    slug: "model-chip",
    category: "Atoms",
    name: "ModelChip",
    isNew: true,
    snark: "Because every dropdown needs a geopolitical status badge.",
    sources: [
      { name: "openai.com", url: "https://openai.com" },
      { name: "anthropic.com", url: "https://www.anthropic.com" },
      { name: "ollama.com", url: "https://ollama.com" },
    ],
    description:
      "Compact model badge with provider, tier tone, context window, and active state. Use it in composers, inspectors, leaderboards, and dense model selectors.",
    examples: [
      {
        title: "Frontier model",
        Demo: () => (
          <ModelChip provider="OpenAI" tier="frontier" context="128k" active>
            GPT-4.1
          </ModelChip>
        ),
        code: `<ModelChip provider="OpenAI" tier="frontier" context="128k" active>
  GPT-4.1
</ModelChip>`,
      },
      {
        title: "Local model",
        Demo: () => (
          <ModelChip provider="local" tier="local" context="32k" size="sm">
            Llama 3.1
          </ModelChip>
        ),
        code: `<ModelChip provider="local" tier="local" context="32k" size="sm">
  Llama 3.1
</ModelChip>`,
      },
    ],
    props: [
      { name: "children", type: "ReactNode", required: true, desc: "Model name or label." },
      { name: "provider", type: "ReactNode", desc: "Provider label." },
      { name: "tier", type: '"frontier" | "classic" | "local" | "custom"', default: '"frontier"', desc: "Positioning tone." },
      { name: "context", type: "ReactNode", desc: "Context window label." },
      { name: "size", type: '"sm" | "md"', default: '"md"', desc: "Badge density." },
      { name: "active", type: "boolean", desc: "Marks the selected model." },
    ],
  },

  {
    slug: "token-badge",
    category: "Atoms",
    name: "TokenBadge",
    isNew: true,
    snark: "Because every prompt needs a receipt.",
    sources: [
      { name: "platform.openai.com", url: "https://platform.openai.com/usage" },
      { name: "vercel.com", url: "https://vercel.com" },
      { name: "linear.app", url: "https://linear.app" },
    ],
    description:
      "Inline token, credit, or cost capsule for prompt surfaces, usage meters, and compact billing readouts.",
    usage:
      "Use `value` for the primary number, `label` for supporting context, and `tone` when the value needs status semantics.",
    examples: [
      {
        title: "Usage row",
        Demo: () => (
          <div style={{ display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" }}>
            <TokenBadge value="12.4k tokens" />
            <TokenBadge value="$0.018" label="est." tone="good" />
            <TokenBadge value="240" label="credits" tone="warn" compact />
          </div>
        ),
        code: `<TokenBadge value="12.4k tokens" />
<TokenBadge value="$0.018" label="est." tone="good" />
<TokenBadge value="240" label="credits" tone="warn" compact />`,
      },
      {
        title: "No icon",
        Demo: () => <TokenBadge value="$4.20" label="daily cap" tone="danger" icon={false} />,
        code: `<TokenBadge value="$4.20" label="daily cap" tone="danger" icon={false} />`,
      },
    ],
    props: [
      { name: "value", type: "ReactNode", required: true, desc: "Primary token, credit, or cost value." },
      { name: "label", type: "ReactNode", desc: "Optional supporting label." },
      { name: "tone", type: '"neutral" | "good" | "warn" | "danger"', default: '"neutral"', desc: "Visual tone." },
      { name: "icon", type: "ReactNode | false", desc: "Leading icon. False hides it." },
      { name: "compact", type: "boolean", desc: "Tightens spacing for dense surfaces." },
    ],
  },

  {
    slug: "confidence-meter",
    category: "Atoms",
    name: "ConfidenceMeter",
    isNew: true,
    snark: "A tiny bar for when the model says trust me.",
    sources: [
      { name: "openai.com", url: "https://openai.com" },
      { name: "linear.app", url: "https://linear.app" },
      { name: "vercel.com", url: "https://vercel.com" },
    ],
    description:
      "Inline confidence bar or segmented score indicator for evals, retrieval quality, and agent certainty. Values are clamped to 0-100 and exposed with progress semantics.",
    examples: [
      {
        title: "Inline retrieval quality",
        Demo: () => (
          <span style={{ display: "inline-flex", alignItems: "center", gap: 10 }}>
            <ConfidenceMeter value={82} label="Retrieval" tone="good" showValue />
          </span>
        ),
        code: `<ConfidenceMeter value={82} label="Retrieval" tone="good" showValue />`,
      },
      {
        title: "Segmented certainty",
        Demo: () => (
          <ConfidenceMeter value={64} label="Agent certainty" tone="warn" segments={5} showValue />
        ),
        code: `<ConfidenceMeter value={64} label="Agent certainty" tone="warn" segments={5} showValue />`,
      },
    ],
    props: [
      { name: "value", type: "number", required: true, desc: "Confidence score from 0-100. Values outside the range are clamped." },
      { name: "label", type: "ReactNode", desc: "Optional inline label before the meter." },
      { name: "tone", type: '"neutral" | "good" | "warn" | "danger"', default: '"neutral"', desc: "Visual tone for the meter fill." },
      { name: "segments", type: "number", desc: "Render equal score segments instead of a continuous bar. Clamped to 2-12 when provided." },
      { name: "showValue", type: "boolean", desc: "Show the clamped numeric value after the meter." },
    ],
  },

  {
    slug: "source-glyph",
    category: "Atoms",
    name: "SourceGlyph",
    isNew: true,
    snark: "A footnote with a credit score.",
    sources: [
      { name: "perplexity.ai", url: "https://www.perplexity.ai" },
      { name: "arc.net", url: "https://arc.net" },
      { name: "notebooklm.google", url: "https://notebooklm.google" },
    ],
    description:
      "Small citation/source marker that renders a logo, index number, or trust state. Use it inline in text, source lists, and evidence rows.",
    examples: [
      {
        title: "Indexed citation",
        Demo: () => (
          <span style={{ display: "inline-flex", gap: 8, alignItems: "center" }}>
            <SourceGlyph index={2} tone="trusted" size="sm" /> Verified source
          </span>
        ),
        code: `<SourceGlyph index={2} tone="trusted" size="sm" />`,
      },
      {
        title: "Logo source",
        Demo: () => <SourceGlyph src={ic("github")} alt="GitHub" />,
        code: `<SourceGlyph src={ic("github")} alt="GitHub" />`,
      },
      {
        title: "Custom marker",
        Demo: () => <SourceGlyph tone="warn">AI</SourceGlyph>,
        code: `<SourceGlyph tone="warn">AI</SourceGlyph>`,
      },
    ],
    props: [
      { name: "children", type: "ReactNode", desc: "Fallback marker content when `src` and `index` are not provided." },
      { name: "index", type: "number", desc: "Citation index shown when no `src` is provided." },
      { name: "src", type: "string", desc: "Logo or source image URL." },
      { name: "alt", type: "string", default: '""', desc: "Accessible label for the image. Empty by default for decorative marks." },
      { name: "tone", type: '"neutral" | "trusted" | "warn" | "danger"', default: '"neutral"', desc: "Trust/risk state." },
      { name: "size", type: '"sm" | "md"', default: '"md"', desc: "Glyph size." },
    ],
  },

  /* ============================ PRIMITIVES ============================ */
  {
    slug: "button",
    category: "Primitives",
    name: "Button",
    snark: "We made the button move so you'd click the button.",
    sources: [
      { name: "v0.app", url: "https://v0.app" },
      { name: "lovable.dev", url: "https://lovable.dev" },
      { name: "anthropic.com", url: "https://www.anthropic.com" },
    ],
    extra: 1200,
    description:
      "Polymorphic button with five variants: glow (pulsing gradient halo), shimmer (animated highlight sweep), ghost (outlined), solid (gradient fill), and wave (pill with an animated rainbow wrapping its bottom border, the MUI 'Edit in Chat' treatment). Pass `as` to render an `<a>` or routed link.",
    examples: [
      {
        title: "All five variants",
        Demo: () => (
          <div style={{ display: "flex", gap: 12, flexWrap: "wrap", alignItems: "center" }}>
            <Button variant="glow" sparkle>Generate</Button>
            <Button variant="shimmer">Start building</Button>
            <Button variant="ghost">Talk to sales</Button>
            <Button variant="solid">Upgrade</Button>
            <Button variant="wave">Request a demo</Button>
          </div>
        ),
        code: `<Button variant="glow" sparkle>Generate</Button>
<Button variant="shimmer">Start building</Button>
<Button variant="ghost">Talk to sales</Button>
<Button variant="solid">Upgrade</Button>
<Button variant="wave">Request a demo</Button>`,
      },
      {
        title: "Sizes",
        Demo: () => (
          <div style={{ display: "flex", gap: 12, alignItems: "center" }}>
            <Button size="sm" variant="ghost">Small</Button>
            <Button variant="ghost">Medium</Button>
            <Button size="lg" variant="ghost">Large</Button>
          </div>
        ),
        code: `<Button size="sm">Small</Button>
<Button>Medium</Button>
<Button size="lg">Large</Button>`,
      },
      {
        title: "Loading",
        Demo: () => <Button variant="glow" loading>Shipping…</Button>,
        code: `<Button variant="glow" loading>Shipping…</Button>`,
      },
      {
        title: "As an anchor",
        Demo: () => (
          <Button as="a" href="#" variant="ghost">
            Read the docs
          </Button>
        ),
        code: `<Button as="a" href="/docs" variant="ghost">Read the docs</Button>`,
      },
    ],
    props: [
      { name: "variant", type: '"glow" | "shimmer" | "ghost" | "solid" | "wave"', default: '"glow"', desc: "Visual style." },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', desc: "Padding + font." },
      { name: "sparkle", type: "boolean", desc: "Append a ✦ after the label." },
      { name: "loading", type: "boolean", desc: "Show spinner + disable." },
      { name: "block", type: "boolean", desc: "Render full-width." },
      { name: "as", type: "ElementType", default: '"button"', desc: "Polymorphic tag." },
    ],
  },

  {
    slug: "sticky-banner",
    category: "Banners",
    name: "StickyBanner",
    snark: "Funding news disguised as utility.",
    sources: [
      { name: "granola.ai", url: "https://www.granola.ai" },
      { name: "vercel.com", url: "https://vercel.com" },
      { name: "linear.app", url: "https://linear.app" },
    ],
    extra: 300,
    description:
      "The sticky top announcement bar. Houses Series A news, beta tags, and 'now in W26' brags. Renders full-width above the nav.",
    examples: [
      {
        title: "Funding bar",
        stretch: true,
        Demo: () => (
          <StickyBanner trailing={<span className="pui-arrow">→</span>}>
            Backed by Y Combinator (W26), we just raised our seed
          </StickyBanner>
        ),
        code: `<StickyBanner trailing="→">
  Backed by Y Combinator (W26), we just raised our seed
</StickyBanner>`,
      },
    ],
    props: [
      { name: "hideSparkle", type: "boolean", desc: "Drop the leading ✦." },
      { name: "trailing", type: "ReactNode", desc: "Trailing accessory (arrow, etc.)." },
    ],
  },

  {
    slug: "eyebrow-pill",
    category: "Primitives",
    name: "EyebrowPill",
    snark: "Where the model name goes when there's nothing else to say.",
    sources: [
      { name: "mistral.ai", url: "https://mistral.ai" },
      { name: "openai.com", url: "https://openai.com" },
      { name: "cohere.com", url: "https://cohere.com" },
    ],
    extra: 500,
    description:
      "The pill that sits above the H1 of every section. Defaults to a pulsing green status dot. Pass `icon={false}` to hide, or any node to replace.",
    examples: [
      {
        title: "Default",
        Demo: () => <EyebrowPill>Now with GPT-5.5 Turbo Vision Pro</EyebrowPill>,
        code: `<EyebrowPill>Now with GPT-5.5 Turbo Vision Pro</EyebrowPill>`,
      },
      {
        title: "Custom icon",
        Demo: () => <EyebrowPill icon={<Sparkle />}>The platform</EyebrowPill>,
        code: `<EyebrowPill icon={<Sparkle />}>The platform</EyebrowPill>`,
      },
    ],
    props: [
      { name: "icon", type: "ReactNode | false", default: "<StatusDot />", desc: "Leading icon. False to hide." },
      { name: "statusColor", type: "string", desc: "Color of the default dot." },
    ],
  },

  /* ============================ HEROES ============================ */
  {
    slug: "rotator",
    category: "Heroes",
    name: "Rotator",
    snark: "Because saying \"everything\" wasn't ambitious enough.",
    sources: [
      { name: "vapi.ai", url: "https://vapi.ai" },
      { name: "cresta.com", url: "https://www.cresta.com" },
      { name: "bland.ai", url: "https://bland.ai" },
      { name: "fal.ai", url: "https://fal.ai" },
    ],
    extra: 30,
    description:
      "Types each word, holds, deletes, advances, repeats, the canonical AI-startup-headline animation. Use `renderWord` for custom treatment, or skip the component entirely and call `useTypewriter()` yourself.",
    examples: [
      {
        title: "Basic",
        Demo: () => (
          <h1 style={{ fontSize: 44, margin: 0, fontWeight: 700 }}>
            AI for{" "}
            <GradientText>
              <Rotator words={["doctors", "lawyers", "founders", "everyone"]} />
            </GradientText>
          </h1>
        ),
        code: `<h1>
  AI for{" "}
  <GradientText>
    <Rotator words={["doctors", "lawyers", "founders", "everyone"]} />
  </GradientText>
</h1>`,
      },
      {
        title: "Faster + no cursor",
        Demo: () => (
          <h2 style={{ fontSize: 32, margin: 0, fontWeight: 700 }}>
            Stop{" "}
            <Rotator
              words={["context-switching", "writing emails", "shipping slop"]}
              typeMs={50}
              holdMs={1000}
              hideCursor
            />
            .
          </h2>
        ),
        code: `<Rotator
  words={["context-switching", "writing emails", "shipping slop"]}
  typeMs={50}
  holdMs={1000}
  hideCursor
/>`,
      },
      {
        title: "Custom word renderer",
        Demo: () => (
          <h2 style={{ fontSize: 28, margin: 0 }}>
            Built for{" "}
            <Rotator
              words={["builders", "thinkers", "doers"]}
              renderWord={(w: string) => <span style={{ borderBottom: "2px solid #ec4899" }}>{w}</span>}
            />
          </h2>
        ),
        code: `<Rotator
  words={["builders", "thinkers", "doers"]}
  renderWord={(w) => <span style={{ borderBottom: "2px solid #ec4899" }}>{w}</span>}
/>`,
      },
    ],
    props: [
      { name: "words", type: "string[]", required: true, desc: "Words to cycle through." },
      { name: "typeMs", type: "number", default: "70", desc: "ms per character (typing)." },
      { name: "deleteMs", type: "number", default: "32", desc: "ms per character (deleting)." },
      { name: "holdMs", type: "number", default: "1500", desc: "ms to hold the full word." },
      { name: "loop", type: "boolean", default: "true", desc: "Restart at the start once finished." },
      { name: "cursor", type: "string", default: '"▍"', desc: "Cursor character." },
      { name: "hideCursor", type: "boolean", desc: "Hide the blinking cursor." },
      { name: "renderWord", type: "(word, index) => ReactNode", desc: "Custom word renderer." },
      { name: "onWordReached", type: "(word, index) => void", desc: "Callback at end of type." },
    ],
  },

  {
    slug: "word-roll",
    category: "Heroes",
    name: "WordRoll",
    snark: "All the breadth-flexing of a Rotator, without making the visitor wait for it to type.",
    sources: [
      { name: "supermemory.ai", url: "https://supermemory.ai" },
      { name: "linear.app", url: "https://linear.app" },
    ],
    extra: 40,
    description:
      "Vertical slide-roll cousin of Rotator. The active word slides in, the previous one slides out, no typing, no cursor. Pass `gradient` to get the AI-pink treatment per-word (don't nest inside `<GradientText>`, background-clip:text doesn't apply to the absolutely-positioned rolling words).",
    examples: [
      {
        title: "Default (roll up)",
        Demo: () => (
          <h2 style={{ fontSize: 40, margin: 0, fontWeight: 700 }}>
            AI for{" "}
            <WordRoll
              words={["doctors", "lawyers", "founders", "everyone"]}
              gradient
            />
          </h2>
        ),
        code: `<h2>
  AI for{" "}
  <WordRoll
    words={["doctors", "lawyers", "founders", "everyone"]}
    gradient
  />
</h2>`,
      },
      {
        title: "Roll down + slower",
        Demo: () => (
          <h2 style={{ fontSize: 32, margin: 0 }}>
            Built for{" "}
            <WordRoll
              words={["builders", "founders", "tinkerers"]}
              direction="down"
              intervalMs={3000}
              transitionMs={700}
            />
          </h2>
        ),
        code: `<WordRoll
  words={["builders", "founders", "tinkerers"]}
  direction="down"
  intervalMs={3000}
  transitionMs={700}
/>`,
      },
    ],
    props: [
      { name: "words", type: "string[]", required: true, desc: "Words to cycle through." },
      { name: "intervalMs", type: "number", default: "2200", desc: "ms each word holds before rolling out." },
      { name: "transitionMs", type: "number", default: "500", desc: "ms of the slide animation itself." },
      { name: "direction", type: '"up" | "down"', default: '"up"', desc: "Direction the active word rolls in from." },
      { name: "gradient", type: "boolean", desc: "Paint each word with the AI gradient. Use instead of nesting in <GradientText>." },
    ],
  },

  {
    slug: "prompt-hero",
    category: "Heroes",
    name: "PromptHero",
    snark: "We replaced the value prop with a text input.",
    sources: [
      { name: "lovable.dev", url: "https://lovable.dev" },
      { name: "bolt.new", url: "https://bolt.new" },
      { name: "v0.app", url: "https://v0.app" },
      { name: "magicpatterns.com", url: "https://www.magicpatterns.com" },
    ],
    extra: 80,
    description:
      "The ChatGPT-box-as-CTA. Pair with a Rotator above and you have an entire homepage in five components.",
    examples: [
      {
        title: "Default",
        Demo: () => (
          <div style={{ width: "100%", maxWidth: 540 }}>
            <PromptHero onSubmit={(t) => alert(`Building: ${t}`)} />
          </div>
        ),
        code: `<PromptHero onSubmit={(text) => navigate(\`/build?q=\${text}\`)} />`,
      },
      {
        title: "Custom CTA + placeholder",
        Demo: () => (
          <div style={{ width: "100%", maxWidth: 540 }}>
            <PromptHero
              placeholder="Paste a tweet, get a landing page…"
              ctaLabel="Ship it"
            />
          </div>
        ),
        code: `<PromptHero
  placeholder="Paste a tweet, get a landing page…"
  ctaLabel="Ship it"
/>`,
      },
    ],
    props: [
      { name: "placeholder", type: "string", default: '"Describe what you want to build…"', desc: "Input placeholder." },
      { name: "value", type: "string", desc: "Controlled value." },
      { name: "defaultValue", type: "string", desc: "Uncontrolled initial value." },
      { name: "onChange", type: "(value: string) => void", desc: "Fired on every keystroke." },
      { name: "onSubmit", type: "(value: string) => void", desc: "Fired on form submit." },
      { name: "leading", type: "ReactNode | false", default: "<Sparkle />", desc: "Leading icon." },
      { name: "ctaLabel", type: "ReactNode", default: '"Generate"', desc: "Submit button label." },
      { name: "hideCta", type: "boolean", desc: "Render input-only." },
    ],
  },

  {
    slug: "prompt",
    category: "Primitives",
    name: "Prompt",
    snark: "The textarea every AI builder ships instead of explaining what their product does.",
    sources: [
      { name: "bolt.new", url: "https://bolt.new" },
      { name: "lovable.dev", url: "https://lovable.dev" },
      { name: "v0.app", url: "https://v0.app" },
      { name: "replit.com", url: "https://replit.com" },
      { name: "chatgpt.com", url: "https://chatgpt.com" },
    ],
    extra: 240,
    description:
      "The multi-line prompt box used by every AI builder. Multi-line textarea on top, toolbar on the bottom: a `+` for adding context, a model dropdown, a microphone for voice mode, and a gradient send button. Cmd/Ctrl+Enter submits.",
    examples: [
      {
        title: "Default",
        stretch: true,
        Demo: () => (
          <div style={{ padding: 24, display: "flex", justifyContent: "center" }}>
            <Prompt
              onSubmit={(text: string, ctx: { model?: string }) =>
                alert(`Building with ${ctx.model}:\n${text}`)
              }
            />
          </div>
        ),
        code: `<Prompt
  onSubmit={(text, { model }) => generate(text, model)}
/>`,
      },
      {
        title: "Custom models + voice/context wired up",
        stretch: true,
        Demo: () => (
          <div style={{ padding: 24, display: "flex", justifyContent: "center" }}>
            <Prompt
              placeholder="Paste a tweet, get a landing page…"
              models={["o4-mini", "Claude Sonnet 4.6", "Llama 4 70B"]}
              defaultModel="Claude Sonnet 4.6"
              onAddContext={() => alert("File picker opens here")}
              onVoice={() => alert("Voice mode")}
              onSubmit={(text: string) => alert("Ship it: " + text)}
            />
          </div>
        ),
        code: `<Prompt
  placeholder="Paste a tweet, get a landing page…"
  models={["o4-mini", "Claude Sonnet 4.6", "Llama 4 70B"]}
  defaultModel="Claude Sonnet 4.6"
  onAddContext={openFilePicker}
  onVoice={startVoiceMode}
  onSubmit={(text) => generate(text)}
/>`,
      },
    ],
    props: [
      { name: "value", type: "string", desc: "Controlled text value." },
      { name: "defaultValue", type: "string", desc: "Uncontrolled initial text." },
      { name: "onChange", type: "(value: string) => void", desc: "Fires on every keystroke." },
      { name: "onSubmit", type: "(value, ctx: {model}) => void", desc: "Fires on submit (button or Cmd/Ctrl+Enter)." },
      { name: "placeholder", type: "string", default: '"Build me a…"', desc: "Textarea placeholder." },
      { name: "rows", type: "number", default: "3", desc: "Initial textarea height in rows." },
      { name: "models", type: "string[]", desc: "Model options for the dropdown." },
      { name: "model", type: "string", desc: "Controlled selected model." },
      { name: "defaultModel", type: "string", desc: "Uncontrolled initial model." },
      { name: "onModelChange", type: "(model: string) => void", desc: "Fires when the user picks a model." },
      { name: "onAddContext", type: "() => void", desc: "Fires when the + button is clicked." },
      { name: "onVoice", type: "() => void", desc: "Fires when the mic button is clicked." },
      { name: "hideAddContext", type: "boolean", desc: "Hide the + button." },
      { name: "hideModel", type: "boolean", desc: "Hide the model dropdown." },
      { name: "hideVoice", type: "boolean", desc: "Hide the mic button." },
      { name: "hideSend", type: "boolean", desc: "Hide the send button." },
      { name: "submitOnCmdEnter", type: "boolean", default: "true", desc: "Submit when Cmd/Ctrl+Enter is pressed." },
      { name: "toolbarExtras", type: "ReactNode", desc: "Extra node rendered just before the mic + send buttons (e.g. a Cmd+↵ hint)." },
    ],
  },

  {
    slug: "ascii-hero",
    category: "Heroes",
    name: "AsciiHero",
    snark: "For hackers, by people who follow the right newsletters.",
    sources: [
      { name: "opencode.ai", url: "https://opencode.ai" },
      { name: "ghostty.org", url: "https://ghostty.org" },
      { name: "terminal.shop", url: "https://terminal.shop" },
      { name: "supermemory.ai", url: "https://supermemory.ai" },
    ],
    extra: 25,
    description:
      "A canvas-rendered procedural ASCII field that reacts to the cursor. The grid auto-fits its container. Two visual modes: `panel` (default, bordered card) and `bare` (no chrome, intended for background use). Flip on `colorful` for the aurora palette and `spotlightOpacity` to brighten the area under the cursor, perfect for low-opacity backgrounds where the user gets rewarded for hovering.",
    examples: [
      {
        title: "Default panel",
        stretch: true,
        Demo: () => (
          <div style={{ padding: 24 }}>
            <AsciiHero />
          </div>
        ),
        code: `<AsciiHero />`,
      },
      {
        title: "Colorful (aurora palette)",
        stretch: true,
        Demo: () => (
          <div style={{ padding: 24 }}>
            <AsciiHero colorful />
          </div>
        ),
        code: `<AsciiHero colorful />`,
      },
      {
        title: "As a hero background (low opacity + cursor spotlight)",
        stretch: true,
        Demo: () => (
          <div
            style={{
              position: "relative",
              minHeight: 280,
              padding: 36,
              overflow: "hidden",
              background: "#08080b",
            }}
          >
            <AsciiHero
              variant="bare"
              colorful
              baseOpacity={0.18}
              spotlightOpacity={0.9}
              spotlightRadius={10}
              style={{ position: "absolute", inset: 0 }}
            />
            <div
              style={{
                position: "relative",
                zIndex: 1,
                textAlign: "center",
                color: "var(--pui-fg)",
              }}
            >
              <h3 style={{ fontSize: 28, margin: "0 0 8px" }}>
                Hover this card.
              </h3>
              <p style={{ margin: 0, color: "var(--pui-fg-dim)" }}>
                The field stays dim until your cursor lights it up.
              </p>
            </div>
          </div>
        ),
        code: `<div style={{ position: "relative" }}>
  <AsciiHero
    variant="bare"
    colorful
    baseOpacity={0.18}
    spotlightOpacity={0.9}
    spotlightRadius={10}
    style={{ position: "absolute", inset: 0 }}
  />
  <div style={{ position: "relative", zIndex: 1 }}>…content…</div>
</div>`,
      },
      {
        title: "Custom palette + ramp",
        stretch: true,
        Demo: () => (
          <div style={{ padding: 24 }}>
            <AsciiHero
              palette={["#22c55e", "#86efac", "#fbbf24"]}
              charRamp=" .:-=+*#%@"
            />
          </div>
        ),
        code: `<AsciiHero
  palette={["#22c55e", "#86efac", "#fbbf24"]}
  charRamp=" .:-=+*#%@"
/>`,
      },
    ],
    props: [
      { name: "variant", type: '"panel" | "bare"', default: '"panel"', desc: "panel = bordered card; bare = no chrome (for background use)." },
      { name: "cols", type: "number", desc: "Grid width in cells. Auto-computed from container if omitted." },
      { name: "rows", type: "number", desc: "Grid height in cells. Auto-computed from container if omitted." },
      { name: "fontSize", type: "number", default: "11", desc: "Character font size (px)." },
      { name: "charRamp", type: "string", desc: "Sparsest → densest characters." },
      { name: "colorful", type: "boolean", desc: "Paint with the default aurora palette." },
      { name: "palette", type: "string[]", desc: "Custom palette; overrides `colorful`." },
      { name: "baseOpacity", type: "number", default: "1", desc: "Base alpha. Drop low (≈ 0.18) for background use." },
      { name: "reactive", type: "boolean", default: "true", desc: "Enable cursor reactivity." },
      { name: "rippleStrength", type: "number", default: "1.4", desc: "Cursor ripple amplitude (changes which chars show)." },
      { name: "rippleRadius", type: "number", default: "6", desc: "Cursor ripple falloff radius (cells)." },
      { name: "spotlightOpacity", type: "number", desc: "Alpha at the cursor center; falls off radially to baseOpacity." },
      { name: "spotlightRadius", type: "number", default: "8", desc: "Cursor spotlight radius (cells)." },
      { name: "frameMs", type: "number", default: "50", desc: "Frame throttle (ms)." },
    ],
  },

  /* ============================ BACKGROUNDS ============================ */
  {
    slug: "aurora",
    category: "Backgrounds",
    name: "Aurora",
    snark: "Three blobs and a generation defined.",
    sources: [
      { name: "vercel.com", url: "https://vercel.com" },
      { name: "linear.app", url: "https://linear.app" },
      { name: "mistral.ai", url: "https://mistral.ai" },
      { name: "openai.com", url: "https://openai.com" },
    ],
    extra: 700,
    description:
      "Drifting radial gradient blobs. Sits absolutely inside its `position: relative` parent. Override `blobs` for any palette you want; in good taste or otherwise.",
    examples: [
      {
        title: "Default purple/pink/cyan",
        stretch: true,
        Demo: () => (
          <div style={{ position: "relative", height: 280, overflow: "hidden", isolation: "isolate" }}>
            <Aurora />
            <div style={{ position: "relative", zIndex: 1, padding: 36, textAlign: "center" }}>
              <h2 style={{ margin: 0, fontSize: 32 }}>Aurora as a hero backdrop</h2>
            </div>
          </div>
        ),
        code: `<div style={{ position: "relative" }}>
  <Aurora />
  <div style={{ position: "relative", zIndex: 1 }}>…</div>
</div>`,
      },
      {
        title: "Lava-lamp animated (blobs push each other around)",
        stretch: true,
        Demo: () => (
          <div style={{ position: "relative", height: 280, overflow: "hidden", isolation: "isolate" }}>
            <Aurora
              animated
              blobs={[
                { color: "rgba(124,58,237,0.55)", x: 30, y: 40, size: 55 },
                { color: "rgba(236,72,153,0.45)", x: 65, y: 35, size: 50 },
                { color: "rgba(6,182,212,0.40)",  x: 55, y: 75, size: 50 },
                { color: "rgba(251,191,36,0.30)", x: 25, y: 70, size: 40 },
              ]}
            />
          </div>
        ),
        code: `<Aurora
  animated
  blobs={[
    { color: "rgba(124,58,237,0.55)", x: 30, y: 40, size: 55 },
    { color: "rgba(236,72,153,0.45)", x: 65, y: 35, size: 50 },
    { color: "rgba(6,182,212,0.40)",  x: 55, y: 75, size: 50 },
    { color: "rgba(251,191,36,0.30)", x: 25, y: 70, size: 40 },
  ]}
/>`,
      },
      {
        title: "Custom palette",
        stretch: true,
        Demo: () => (
          <div style={{ position: "relative", height: 220, overflow: "hidden" }}>
            <Aurora
              blobs={[
                { color: "rgba(34,197,94,0.45)", x: 25, y: 30, size: 55 },
                { color: "rgba(251,191,36,0.4)", x: 75, y: 60, size: 45 },
              ]}
            />
          </div>
        ),
        code: `<Aurora blobs={[
  { color: "rgba(34,197,94,0.45)", x: 25, y: 30, size: 55 },
  { color: "rgba(251,191,36,0.4)",  x: 75, y: 60, size: 45 },
]} />`,
      },
    ],
    props: [
      { name: "blobs", type: "{color,x,y,size?}[]", desc: "Color stops with positions (0–100%)." },
      { name: "blur", type: "number", default: "50", desc: "CSS blur in px." },
      { name: "static", type: "boolean", desc: "Disable the slow drift." },
      { name: "animated", type: "boolean", desc: "Lava-lamp mode, blobs become independent bubbles that push each other around. Overrides the CSS drift." },
      { name: "repulsion", type: "number", default: "0.18", desc: "When animated, how aggressively blobs push each other apart (0 disables interaction)." },
    ],
  },

  {
    slug: "node-graph",
    category: "Backgrounds",
    name: "NodeGraphBackground",
    snark: "A neural network, conceptually.",
    sources: [
      { name: "pinecone.io", url: "https://www.pinecone.io" },
      { name: "cerebras.ai", url: "https://cerebras.ai" },
      { name: "scale.com", url: "https://scale.com" },
      { name: "deepgram.com", url: "https://deepgram.com" },
    ],
    extra: 220,
    description:
      "Canvas-rendered drifting nodes with proximity-based links. Reacts to the cursor (pulls nodes within `hoverDistance`). Zero JS dependencies.",
    examples: [
      {
        title: "Default",
        stretch: true,
        Demo: () => (
          <div style={{ position: "relative", height: 280, overflow: "hidden", background: "#08080b" }}>
            <NodeGraphBackground />
          </div>
        ),
        code: `<div style={{ position: "relative", height: 280 }}>
  <NodeGraphBackground />
</div>`,
      },
      {
        title: "Sparse + green",
        stretch: true,
        Demo: () => (
          <div style={{ position: "relative", height: 240, overflow: "hidden", background: "#08080b" }}>
            <NodeGraphBackground
              density={35}
              linkColor="#22c55e"
              colors={["#86efac", "#22c55e"]}
              linkDistance={180}
            />
          </div>
        ),
        code: `<NodeGraphBackground
  density={35}
  linkColor="#22c55e"
  colors={["#86efac", "#22c55e"]}
  linkDistance={180}
/>`,
      },
    ],
    props: [
      { name: "density", type: "number", default: "70", desc: "Number of nodes." },
      { name: "speed", type: "number", default: "0.4", desc: "Pixel speed per frame." },
      { name: "linkDistance", type: "number", default: "140", desc: "Max px between linked nodes." },
      { name: "colors", type: "string[]", desc: "Pool of node colors." },
      { name: "linkColor", type: "string", default: '"#7c3aed"', desc: "Link stroke color." },
      { name: "baseOpacity", type: "number", default: "0.45", desc: "Resting alpha of nodes + edges. Field is dim at rest; cursor brightens it." },
      { name: "hoverDistance", type: "number", default: "200", desc: "Radius of cursor effects (gravity + brighten). 0 disables both." },
      { name: "hoverGravity", type: "number", default: "0.005", desc: "0–1 strength of cursor pull. Default is very subtle drift; set higher for stronger attraction." },
      { name: "hoverBrighten", type: "number", default: "0.8", desc: "0–1 strength of opacity boost near the cursor." },
      { name: "overscan", type: "number", default: "80", desc: "px the simulation world extends past the visible viewport, nodes bounce off the world edges, drifting in/out of view." },
    ],
  },

  {
    slug: "floating-sparkles",
    category: "Backgrounds",
    name: "FloatingSparkles",
    snark: "Magic doesn't ship itself.",
    sources: [
      { name: "notion.com/product/ai", url: "https://www.notion.com/product/ai" },
      { name: "granola.ai", url: "https://www.granola.ai" },
    ],
    extra: 90,
    description:
      "A field of ✦ glyphs drifting upward. Pure CSS, randomized once per mount. Drop inside any `position: relative` parent.",
    examples: [
      {
        title: "Default",
        stretch: true,
        Demo: () => (
          <div style={{ position: "relative", height: 240, overflow: "hidden", background: "#0a0a12" }}>
            <FloatingSparkles />
          </div>
        ),
        code: `<div style={{ position: "relative", height: 240 }}>
  <FloatingSparkles />
</div>`,
      },
      {
        title: "Denser + emoji",
        stretch: true,
        Demo: () => (
          <div style={{ position: "relative", height: 220, overflow: "hidden", background: "#0a0a12" }}>
            <FloatingSparkles
              count={40}
              glyphs={["✨", "⭐", "💫"]}
              sizeRange={[10, 22]}
              durationS={[5, 12]}
            />
          </div>
        ),
        code: `<FloatingSparkles
  count={40}
  glyphs={["✨", "⭐", "💫"]}
  sizeRange={[10, 22]}
  durationS={[5, 12]}
/>`,
      },
    ],
    props: [
      { name: "count", type: "number", default: "18", desc: "Number of sparkles." },
      { name: "glyphs", type: "string[]", desc: "Pool of glyphs." },
      { name: "durationS", type: "[number, number]", default: "[8, 18]", desc: "[min, max] seconds." },
      { name: "sizeRange", type: "[number, number]", default: "[8, 20]", desc: "[min, max] px font size." },
    ],
  },

  /* ============================ SURFACES ============================ */
  {
    slug: "glass-card",
    category: "Surfaces",
    name: "GlassCard",
    snark: "Backdrop-filter: ambition.",
    sources: [
      { name: "vercel.com", url: "https://vercel.com" },
      { name: "linear.app", url: "https://linear.app" },
      { name: "openai.com", url: "https://openai.com" },
    ],
    extra: 1500,
    description:
      "Glassmorphism feature card. Compound parts let you rearrange or swap sections. `breathing` toggles a slow box-shadow pulse; `glowOnHover` reveals a gradient halo on hover.",
    examples: [
      {
        title: "Default with all parts",
        Demo: () => (
          <div style={{ width: 320 }}>
            <GlassCard breathing>
              <GlassCard.Icon>✦</GlassCard.Icon>
              <GlassCard.Title>Reason</GlassCard.Title>
              <GlassCard.Body>
                A frontier-class reasoning engine. Multi-step. Multi-modal.
                Multi-vendor.
              </GlassCard.Body>
              <GlassCard.Link href="#">Learn more</GlassCard.Link>
            </GlassCard>
          </div>
        ),
        code: `<GlassCard breathing>
  <GlassCard.Icon>✦</GlassCard.Icon>
  <GlassCard.Title>Reason</GlassCard.Title>
  <GlassCard.Body>A frontier-class reasoning engine.</GlassCard.Body>
  <GlassCard.Link href="/learn">Learn more</GlassCard.Link>
</GlassCard>`,
      },
    ],
    props: [
      { name: "breathing", type: "boolean", desc: "Slow shadow pulse." },
      { name: "glowOnHover", type: "boolean", default: "true", desc: "Gradient halo on hover." },
    ],
    subprops: [
      { name: "GlassCard.Icon", props: [] },
      { name: "GlassCard.Title", props: [] },
      { name: "GlassCard.Body", props: [] },
      { name: "GlassCard.Link", props: [{ name: "href", type: "string", desc: "Anchor target." }] },
    ],
  },

  {
    slug: "mock-ide",
    category: "Surfaces",
    name: "MockIDE",
    snark: "Real code is coming. This is the trailer.",
    sources: [
      { name: "cursor.com", url: "https://cursor.com" },
      { name: "v0.app", url: "https://v0.app" },
      { name: "cognition.ai", url: "https://www.cognition.ai" },
      { name: "magic.dev", url: "https://magic.dev" },
    ],
    extra: 65,
    description:
      "Mock IDE that streams pretokenized code character-by-character with a blinking caret. Pass an array of `IdeToken` objects; each has a class hint for color (key, str, num, com, fn).",
    examples: [
      {
        title: "Streaming TS handler",
        stretch: true,
        Demo: () => (
          <div style={{ padding: 24 }}>
            <MockIDE
              filename="~/synthetica/app/api/route.ts"
              tokens={SAMPLE_TOKENS}
              thinkingLabel="AI is writing…"
            />
          </div>
        ),
        code: `<MockIDE
  filename="~/synthetica/app/api/route.ts"
  tokens={[
    { c: "// generated by synthetica\\n", cls: "com" },
    { c: "export async function ", cls: "key" },
    { c: "POST", cls: "fn" },
    { c: "(req: Request) {\\n" },
    // …
  ]}
/>`,
      },
    ],
    props: [
      { name: "filename", type: "string", desc: "Shown in the tab." },
      { name: "tokens", type: "IdeToken[]", desc: "Source tokens to type out." },
      { name: "loop", type: "boolean", default: "true", desc: "Restart after a 3s pause." },
      { name: "charMs", type: "[number, number]", default: "[14, 42]", desc: "Per-char delay range." },
      { name: "thinkingLabel", type: "ReactNode | false", default: '"AI is writing…"', desc: "Pill label; false to hide." },
    ],
    subprops: [
      {
        name: "MockIDE.Chrome",
        props: [
          { name: "filename", type: "string", desc: "Tab label." },
          { name: "thinking", type: "ReactNode | false", desc: "Pill content." },
        ],
      },
      {
        name: "MockIDE.Body",
        props: [
          { name: "tokens", type: "IdeToken[]", required: true, desc: "Tokens to stream." },
          { name: "loop", type: "boolean", desc: "Loop after finishing." },
        ],
      },
    ],
  },

  /* ============================ CONVERSATION ============================ */
  {
    slug: "chat-bubble",
    category: "Conversation",
    name: "ChatBubble",
    snark: "If it's in a bubble, it must be true.",
    sources: [
      { name: "chatgpt.com", url: "https://chatgpt.com" },
      { name: "claude.ai", url: "https://claude.ai" },
      { name: "perplexity.ai", url: "https://perplexity.ai" },
      { name: "sierra.ai", url: "https://sierra.ai" },
    ],
    extra: 250,
    description:
      "Chat bubbles for fake conversations. AI bubbles ship with a meta row (sparkle + agent name + thinking pill); replace any of those by passing props or `false`.",
    examples: [
      {
        title: "User + AI",
        Demo: () => (
          <div style={{ display: "flex", flexDirection: "column", gap: 12, width: "100%" }}>
            <ChatBubble role="user">
              Summarize Q3 churn by cohort and tell me what's bleeding.
            </ChatBubble>
            <ChatBubble role="ai" agent="Synthetica" thinking="reasoning…">
              Q3 churn is bleeding from your SMB cohort. Net retention is 71%
              vs. 104% in mid-market.
            </ChatBubble>
          </div>
        ),
        code: `<ChatBubble role="user">Summarize Q3 churn…</ChatBubble>
<ChatBubble role="ai" agent="Synthetica" thinking="reasoning…">
  Q3 churn is bleeding from your SMB cohort…
</ChatBubble>`,
      },
    ],
    props: [
      { name: "role", type: '"user" | "ai"', required: true, desc: "Bubble direction + styling." },
      { name: "agent", type: "ReactNode", desc: "Agent name (AI bubbles)." },
      { name: "thinking", type: "ReactNode | false", desc: "Thinking pill content; false to hide." },
      { name: "icon", type: "ReactNode | false", desc: "Leading icon override." },
    ],
  },

  {
    slug: "token-stream",
    category: "Conversation",
    name: "TokenStream",
    snark: "Server-sent events (SSE) were added to the HTML5 spec in 2008 but never used until 2025.",
    sources: [
      { name: "chatgpt.com", url: "https://chatgpt.com" },
      { name: "claude.ai", url: "https://claude.ai" },
      { name: "perplexity.ai", url: "https://perplexity.ai" },
    ],
    extra: 1800,
    description:
      "Reveals a string token-by-token with a trailing blinking caret. Pair with a `<ChatBubble role='ai'>` for the platonic 'reasoning, but visibly' demo. Bring your own tokenizer.",
    examples: [
      {
        title: "Inside an AI bubble",
        Demo: () => (
          <ChatBubble role="ai" agent="Synthetica" thinking="reasoning…">
            <TokenStream
              text="Q3 churn is bleeding from your SMB cohort. Net retention there is 71% vs. 104% in mid-market and 118% in enterprise."
              loop
            />
          </ChatBubble>
        ),
        code: `<ChatBubble role="ai" agent="Synthetica" thinking="reasoning…">
  <TokenStream
    text="Q3 churn is bleeding from your SMB cohort…"
    loop
  />
</ChatBubble>`,
      },
      {
        title: "Per-character (custom tokenizer)",
        Demo: () => (
          <div style={{ fontFamily: "var(--pui-font-mono)", fontSize: 14 }}>
            <TokenStream
              text="reasoning, token by token by token…"
              tokenize={(s: string) => s.split("")}
              speedMs={45}
              loop
            />
          </div>
        ),
        code: `<TokenStream
  text="reasoning, token by token by token…"
  tokenize={(s) => s.split("")}
  speedMs={45}
  loop
/>`,
      },
    ],
    props: [
      { name: "text", type: "string", required: true, desc: "The full text to reveal." },
      { name: "speedMs", type: "number | [number, number]", default: "[18, 80]", desc: "Per-token delay (range = jitter)." },
      { name: "tokenize", type: "(s: string) => string[]", desc: "Custom splitter. Default: words + whitespace." },
      { name: "loop", type: "boolean", desc: "Loop after a delay." },
      { name: "loopDelayMs", type: "number", default: "6000", desc: "Pause before restarting." },
      { name: "hideCaret", type: "boolean", desc: "Hide the trailing caret." },
      { name: "onComplete", type: "() => void", desc: "Fired when full text is shown." },
    ],
  },

  {
    slug: "chat-fab",
    category: "Conversation",
    name: "ChatFAB",
    snark: "There's no escape now.",
    sources: [
      { name: "intercom.com (Fin)", url: "https://www.intercom.com/fin" },
      { name: "sierra.ai", url: "https://sierra.ai" },
      { name: "decagon.ai", url: "https://decagon.ai" },
    ],
    extra: 320,
    description:
      "Bottom-right floating 'Ask AI' button with a popover. Compose ChatFAB.Header and ChatFAB.Body for the popover contents; the close button uses context so it just works.",
    examples: [
      {
        title: "Default (click to open)",
        Demo: () => (
          <div style={{ position: "relative", minHeight: 200, width: "100%" }}>
            <p style={{ textAlign: "center", color: "var(--pui-fg-mute)" }}>
              The FAB is fixed-positioned to the viewport, so it's docked
              bottom-right of your window, not this card.
            </p>
            <ChatFAB
              popover={
                <>
                  <ChatFAB.Header>Hi, I'm Synthi.</ChatFAB.Header>
                  <ChatFAB.Body>
                    <p style={{ margin: 0, color: "var(--pui-fg-dim)" }}>
                      Ask me anything about Synthetica.
                    </p>
                  </ChatFAB.Body>
                </>
              }
            />
          </div>
        ),
        code: `<ChatFAB
  popover={<>
    <ChatFAB.Header>Hi, I'm Synthi.</ChatFAB.Header>
    <ChatFAB.Body>Ask me anything.</ChatFAB.Body>
  </>}
/>`,
      },
    ],
    props: [
      { name: "label", type: "ReactNode", default: '"Ask AI"', desc: "Button label." },
      { name: "open", type: "boolean", desc: "Controlled open state." },
      { name: "defaultOpen", type: "boolean", desc: "Uncontrolled initial state." },
      { name: "onOpenChange", type: "(open: boolean) => void", desc: "Open-state callback." },
      { name: "popover", type: "ReactNode", desc: "Popover contents." },
    ],
  },

  /* ============================ SOCIAL PROOF ============================ */
  {
    slug: "logo-marquee",
    category: "Social Proof",
    name: "LogoMarquee",
    snark:
      "Trusted by everyone you've heard of, including the ones that didn't sign.",
    sources: [
      { name: "glean.com", url: "https://www.glean.com" },
      { name: "decagon.ai", url: "https://decagon.ai" },
      { name: "cresta.com", url: "https://www.cresta.com" },
      { name: "harvey.ai", url: "https://www.harvey.ai" },
      { name: "sierra.ai", url: "https://sierra.ai" },
    ],
    extra: 900,
    description:
      "Infinite-scroll logo wall. Mix `img` and `node` entries to combine real logos (via simple-icons) with text-only ones (Bloomberg, NASA, Harvard). Duplicates the track for a seamless loop.",
    examples: [
      {
        title: "Real + text logos",
        stretch: true,
        Demo: () => (
          <LogoMarquee
            logos={[
              { kind: "img", src: ic("openai"), alt: "OpenAI" },
              { kind: "img", src: ic("stripe"), alt: "Stripe" },
              { kind: "img", src: ic("anthropic"), alt: "Anthropic" },
              { kind: "node", node: <span className="pui-marquee__text">NASA</span> },
              { kind: "img", src: ic("notion"), alt: "Notion" },
              { kind: "img", src: ic("shopify"), alt: "Shopify" },
              {
                kind: "node",
                node: <span className="pui-marquee__text pui-marquee__text--serif pui-marquee__text--italic">Harvard</span>,
              },
              { kind: "img", src: ic("vercel"), alt: "Vercel" },
              { kind: "img", src: ic("github"), alt: "GitHub" },
              { kind: "img", src: ic("nvidia"), alt: "NVIDIA" },
            ]}
            speed={30}
          />
        ),
        code: `<LogoMarquee
  logos={[
    { kind: "img",  src: openaiSvgUrl, alt: "OpenAI" },
    { kind: "img",  src: stripeSvgUrl, alt: "Stripe" },
    { kind: "node", node: <span className="pui-marquee__text">NASA</span> },
    // …
  ]}
  speed={30}
/>`,
      },
    ],
    props: [
      { name: "logos", type: "MarqueeItem[]", required: true, desc: "Mix of img/node entries." },
      { name: "speed", type: "number", default: "40", desc: "Seconds per loop." },
      { name: "gap", type: "number", default: "56", desc: "Pixel gap between items." },
      { name: "fade", type: "boolean", default: "true", desc: "Edge-fade mask." },
      { name: "pauseOnHover", type: "boolean", desc: "Pause animation on hover." },
    ],
  },

  {
    slug: "logo-row",
    category: "Social Proof",
    name: "LogoRow",
    snark: "Static logos are for when you only have six.",
    sources: [
      { name: "anthropic.com", url: "https://www.anthropic.com" },
      { name: "elicit.com", url: "https://elicit.com" },
      { name: "consensus.app", url: "https://consensus.app" },
    ],
    extra: 400,
    description:
      "Static row of logos with an uppercase eyebrow. Works equally well for 'Backed by', 'From alumni of', or 'As seen in'.",
    examples: [
      {
        title: "Backed by",
        Demo: () => (
          <LogoRow
            heading="Backed by"
            logos={[
              { kind: "img", src: ic("ycombinator"), alt: "YC" },
              { kind: "node", node: "a16z" },
              {
                kind: "node",
                node: <span style={{ fontFamily: "var(--pui-font-serif)", fontStyle: "italic" }}>Sequoia</span>,
              },
              { kind: "node", node: "FOUNDERS FUND" },
              { kind: "node", node: <span style={{ fontStyle: "italic" }}>…and 47 angels you've heard of</span> },
            ]}
          />
        ),
        code: `<LogoRow
  heading="Backed by"
  logos={[
    { kind: "img",  src: ycSvgUrl, alt: "YC" },
    { kind: "node", node: "a16z" },
    { kind: "node", node: <em>Sequoia</em> },
  ]}
/>`,
      },
    ],
    props: [
      { name: "heading", type: "ReactNode", desc: "Uppercase header copy." },
      { name: "logos", type: "LogoRowItem[]", required: true, desc: "Mix of img/node entries." },
    ],
  },

  {
    slug: "stat-counter",
    category: "Social Proof",
    name: "StatCounter",
    snark: "Numbers that go up are better than numbers that don't.",
    sources: [
      { name: "mistral.ai", url: "https://mistral.ai" },
      { name: "openai.com", url: "https://openai.com" },
      { name: "ollama.com", url: "https://ollama.com" },
    ],
    extra: 600,
    description:
      "Animates a number from `from` (default 0) to `target` over `durationMs`. Pass `format` to control display. Or skip the component entirely and use `useCounter()` to drive your own UI.",
    examples: [
      {
        title: "Builders count",
        Demo: () => (
          <h2 style={{ fontSize: 40, margin: 0 }}>
            Join{" "}
            <GradientText>
              <StatCounter target={8247} />
            </GradientText>{" "}
            builders.
          </h2>
        ),
        code: `<StatCounter target={8247} />`,
      },
      {
        title: "Currency",
        Demo: () => (
          <h2 style={{ fontSize: 40, margin: 0 }}>
            <StatCounter target={42_500_000} format={(n: number) => "$" + n.toLocaleString()} />
          </h2>
        ),
        code: `<StatCounter target={42_500_000} format={(n) => \`$\${n.toLocaleString()}\`} />`,
      },
    ],
    props: [
      { name: "target", type: "number", required: true, desc: "End value." },
      { name: "from", type: "number", default: "0", desc: "Start value." },
      { name: "durationMs", type: "number", default: "1800", desc: "Total animation length." },
      { name: "ease", type: "(t: number) => number", desc: "Custom easing (default ease-out-cubic)." },
      { name: "format", type: "(n: number) => string", desc: "Display format." },
    ],
  },

  {
    slug: "community-badge",
    category: "Social Proof",
    name: "CommunityBadge",
    snark: "Stars are the new MAU.",
    sources: [
      { name: "ollama.com", url: "https://ollama.com" },
      { name: "langchain.com", url: "https://www.langchain.com" },
      { name: "fal.ai", url: "https://fal.ai" },
      { name: "together.ai", url: "https://together.ai" },
    ],
    extra: 180,
    description:
      "The 'Star us on GitHub' / 'Join the Discord' tile. Pass `icon` for a URL or `iconNode` for full control.",
    examples: [
      {
        title: "Trio",
        Demo: () => (
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 12, width: "100%" }}>
            <CommunityBadge
              href="#"
              icon={ic("github")}
              title="Star us on GitHub"
              subtitle={<><strong>12,847</strong> stars · +184 this week</>}
            />
            <CommunityBadge
              href="#"
              icon={ic("discord")}
              title="Join the Discord"
              subtitle="8,201 online now"
            />
            <CommunityBadge
              href="#"
              icon={ic("x")}
              title="Follow on X"
              subtitle="build in public, always"
            />
          </div>
        ),
        code: `<CommunityBadge
  href="https://github.com/…"
  icon={githubSvgUrl}
  title="Star us on GitHub"
  subtitle={<><b>12,847</b> stars · +184 this week</>}
/>`,
      },
    ],
    props: [
      { name: "icon", type: "string", desc: "SVG URL (gets inverted via CSS filter)." },
      { name: "iconNode", type: "ReactNode", desc: "Custom icon node." },
      { name: "title", type: "ReactNode", required: true, desc: "Primary label." },
      { name: "subtitle", type: "ReactNode", required: true, desc: "Secondary label (counts, captions)." },
      { name: "href", type: "string", desc: "Anchor target (renders as `<a>`)." },
    ],
  },

  /* ============================ PRICING ============================ */
  {
    slug: "pricing-card",
    category: "Pricing & Conversion",
    name: "PricingCard",
    snark: "The middle one is glowing. Choose accordingly.",
    sources: [
      { name: "vercel.com/pricing", url: "https://vercel.com/pricing" },
      { name: "linear.app/pricing", url: "https://linear.app/pricing" },
      { name: "anthropic.com/pricing", url: "https://www.anthropic.com/pricing" },
    ],
    extra: 5000,
    description:
      "Compound pricing tile. The `featured` prop applies the gradient border + lift used for the 'Most popular' tier. Compose any subset of subcomponents in any order.",
    examples: [
      {
        title: "Three tiers",
        Demo: () => (
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14, width: "100%" }}>
            <PricingCard>
              <PricingCard.Tier>Hobby</PricingCard.Tier>
              <PricingCard.Amount unit="/mo">$0</PricingCard.Amount>
              <PricingCard.Blurb>For weekend experiments.</PricingCard.Blurb>
              <PricingCard.Features>
                <li>10K tokens / day</li>
                <li>Community support</li>
              </PricingCard.Features>
              <PricingCard.CTA href="#">Start free</PricingCard.CTA>
            </PricingCard>
            <PricingCard featured>
              <PricingCard.Flag>Most popular</PricingCard.Flag>
              <PricingCard.Tier>Pro</PricingCard.Tier>
              <PricingCard.Amount unit="/mo">$49</PricingCard.Amount>
              <PricingCard.Blurb>For the serious solo builder.</PricingCard.Blurb>
              <PricingCard.Features>
                <li>1M tokens / day</li>
                <li>Priority routing</li>
                <li>Unlimited projects</li>
              </PricingCard.Features>
              <PricingCard.CTA href="#">Upgrade</PricingCard.CTA>
            </PricingCard>
            <PricingCard>
              <PricingCard.Tier>Enterprise</PricingCard.Tier>
              <PricingCard.Amount>Custom</PricingCard.Amount>
              <PricingCard.Blurb>For teams who say "leverage" a lot.</PricingCard.Blurb>
              <PricingCard.Features>
                <li>VPC deploy</li>
                <li>SOC 2 / HIPAA</li>
              </PricingCard.Features>
              <PricingCard.CTA href="#">Talk to sales</PricingCard.CTA>
            </PricingCard>
          </div>
        ),
        code: `<PricingCard featured>
  <PricingCard.Flag>Most popular</PricingCard.Flag>
  <PricingCard.Tier>Pro</PricingCard.Tier>
  <PricingCard.Amount unit="/mo">$49</PricingCard.Amount>
  <PricingCard.Blurb>For the serious solo builder.</PricingCard.Blurb>
  <PricingCard.Features>
    <li>1M tokens / day</li>
    <li>Priority routing</li>
  </PricingCard.Features>
  <PricingCard.CTA href="/upgrade">Upgrade</PricingCard.CTA>
</PricingCard>`,
      },
    ],
    props: [
      { name: "featured", type: "boolean", desc: "Gradient border + glow + lift." },
    ],
    subprops: [
      { name: "PricingCard.Flag", props: [{ name: "hideSparkle", type: "boolean", desc: "Drop the leading ✦." }] },
      { name: "PricingCard.Tier", props: [] },
      { name: "PricingCard.Amount", props: [{ name: "unit", type: "ReactNode", desc: "Suffix like /mo." }] },
      { name: "PricingCard.Blurb", props: [] },
      { name: "PricingCard.Features", props: [] },
      { name: "PricingCard.CTA", props: [{ name: "href", type: "string", desc: "Anchor target." }] },
    ],
  },

  {
    slug: "before-after",
    category: "Pricing & Conversion",
    name: "BeforeAfter",
    snark: "On the left: chaos. On the right: us.",
    sources: [
      { name: "notion.com/product/ai", url: "https://www.notion.com/product/ai" },
      { name: "granola.ai", url: "https://www.granola.ai" },
      { name: "otter.ai", url: "https://otter.ai" },
    ],
    extra: 850,
    description:
      "Side-by-side comparison. The left panel is muted + struck-through; the right glows. Pass `before`/`after` arrays for the lazy version, or compose subcomponents for full control.",
    examples: [
      {
        title: "Quick form",
        stretch: true,
        Demo: () => (
          <div style={{ padding: 24 }}>
            <BeforeAfter
              brand="Synthetica"
              before={[
                "14 tabs open",
                "3 hours of meetings about meetings",
                "Vibes-based prioritization",
              ]}
              after={[
                "One pane of glass",
                "Async by default",
                "Outcome-driven",
              ]}
            />
          </div>
        ),
        code: `<BeforeAfter
  brand="Synthetica"
  before={[
    "14 tabs open",
    "3 hours of meetings about meetings",
    "Vibes-based prioritization",
  ]}
  after={[
    "One pane of glass",
    "Async by default",
    "Outcome-driven",
  ]}
/>`,
      },
    ],
    props: [
      { name: "before", type: "ReactNode[]", desc: "Quick-form before items." },
      { name: "after", type: "ReactNode[]", desc: "Quick-form after items." },
      { name: "brand", type: "ReactNode", desc: "Name shown over the arrow." },
      { name: "beforeLabel", type: "ReactNode", default: '"Before"', desc: "Override label." },
      { name: "afterLabel", type: "ReactNode", default: '"After"', desc: "Override label." },
    ],
    subprops: [
      { name: "BeforeAfter.Before", props: [{ name: "label", type: "ReactNode", desc: "Tag label." }] },
      { name: "BeforeAfter.Arrow", props: [{ name: "brand", type: "ReactNode", desc: "Brand label." }] },
      { name: "BeforeAfter.After", props: [{ name: "label", type: "ReactNode", desc: "Tag label." }] },
    ],
  },

  {
    slug: "waitlist-form",
    category: "Pricing & Conversion",
    name: "WaitlistForm",
    snark: "Demand we manufactured ourselves.",
    sources: [
      { name: "lindy.ai", url: "https://www.lindy.ai" },
      { name: "magic.dev", url: "https://magic.dev" },
      { name: "reflect.app", url: "https://reflect.app" },
    ],
    extra: 2400,
    description:
      "Inline email-capture. Pair with a `<StatCounter target={8247} />` above for the obligatory 'Join 8,247 builders' headline.",
    examples: [
      {
        title: "Default",
        Demo: () => (
          <WaitlistForm
            footnote="We email when something actually ships."
            onSubmit={(email: string) =>
              alert("Welcome to the waitlist, " + email)
            }
          />
        ),
        code: `<WaitlistForm
  footnote="We email when something actually ships."
  onSubmit={(email) => createWaitlistEntry(email)}
/>`,
      },
    ],
    props: [
      { name: "placeholder", type: "string", default: '"you@startup.ai"', desc: "Input placeholder." },
      { name: "defaultValue", type: "string", desc: "Initial email value." },
      { name: "ctaLabel", type: "ReactNode", default: '"Notify me"', desc: "Submit button label." },
      { name: "leading", type: "ReactNode | false", desc: "Leading icon. Defaults to an envelope SVG; pass false to remove or any node to replace." },
      { name: "footnote", type: "ReactNode", desc: "Small line of text rendered below the form." },
      { name: "onSubmit", type: "(email: string) => void", desc: "Submit callback." },
    ],
  },

  /* ============================ ANOTHER SET ============================ */
  {
    slug: "model-leaderboard",
    category: "Social Proof",
    name: "ModelLeaderboard",
    isNew: true,
    snark: "Benchmarks, but conveniently cropped.",
    sources: [
      { name: "artificialanalysis.ai", url: "https://artificialanalysis.ai" },
      { name: "lmarena.ai", url: "https://lmarena.ai" },
      { name: "openai.com", url: "https://openai.com" },
    ],
    extra: 1120,
    description:
      "A ranked benchmark panel for model claims, eval theater, and suspiciously specific latency bragging. Pass `models` for the quick form or compose rows manually.",
    examples: [
      {
        title: "Eval board",
        Demo: () => (
          <ModelLeaderboard
            title="Frontier evals"
            caption="Weighted for demos, decks, and investor memory."
            metricLabel="SWE-bench-ish"
            models={[
              { name: "Synthetica Max", vendor: "internal", score: 98.7, label: "98.7", delta: "+4.2", tone: "good" },
              { name: "Consensus 4.1", vendor: "frontier", score: 91.4, label: "91.4", delta: "+1.1" },
              { name: "Legacy Copilot", vendor: "classic", score: 72.8, label: "72.8", delta: "-3.0", tone: "warn" },
            ]}
          />
        ),
        code: `<ModelLeaderboard
  title="Frontier evals"
  metricLabel="SWE-bench-ish"
  models={[
    { name: "Synthetica Max", vendor: "internal", score: 98.7, label: "98.7", delta: "+4.2", tone: "good" },
    { name: "Consensus 4.1", vendor: "frontier", score: 91.4, label: "91.4" },
    { name: "Legacy Copilot", vendor: "classic", score: 72.8, label: "72.8", tone: "warn" },
  ]}
/>`,
      },
    ],
    props: [
      { name: "models", type: "ModelLeaderboardModel[]", desc: "Quick-form ranked model rows." },
      { name: "title", type: "ReactNode", desc: "Optional panel heading." },
      { name: "caption", type: "ReactNode", desc: "Optional supporting copy." },
      { name: "metricLabel", type: "ReactNode", desc: "Small label for the score column." },
      { name: "maxScore", type: "number", default: "100", desc: "Score used to normalize bar width." },
      { name: "compact", type: "boolean", default: "false", desc: "Reduce padding and row height." },
      { name: "animated", type: "boolean", default: "true", desc: "Enable row/bar entrance motion." },
    ],
    subprops: [
      { name: "ModelLeaderboard.Row", props: [
        { name: "score", type: "number", desc: "Score used for the bar fill." },
        { name: "maxScore", type: "number", default: "100", desc: "Score maximum." },
        { name: "tone", type: '"neutral" | "good" | "warn" | "danger"', desc: "Row tone." },
      ] },
      { name: "ModelLeaderboard.Name", props: [{ name: "vendor", type: "ReactNode", desc: "Small vendor label." }] },
      { name: "ModelLeaderboard.Score", props: [{ name: "delta", type: "ReactNode", desc: "Small delta shown beside the score." }] },
    ],
  },

  {
    slug: "agent-runway",
    category: "Surfaces",
    name: "AgentRunway",
    isNew: true,
    snark: "Multi-agent orchestration, now with choreography.",
    sources: [
      { name: "cursor.com", url: "https://cursor.com" },
      { name: "replit.com", url: "https://replit.com" },
      { name: "linear.app", url: "https://linear.app" },
    ],
    extra: 990,
    description:
      "A sequential handoff surface for agent teams, background tools, and build pipelines. Use it when the product needs to make invisible automation feel legible.",
    examples: [
      {
        title: "Agent handoff",
        stretch: true,
        Demo: () => (
          <div style={{ padding: 24 }}>
            <AgentRunway
              title="Launch crew"
              summary="Every role gets a lane, a status, and just enough output to look supervised."
              items={[
                { name: "Planner", role: "strategy", output: "Scoped the investor-safe narrative.", status: "done" },
                { name: "Builder", role: "interface", output: "Assembling the conversion surface.", status: "running" },
                { name: "Reviewer", role: "taste", output: "Waiting to reject generic cards.", status: "idle" },
              ]}
            />
          </div>
        ),
        code: `<AgentRunway
  title="Launch crew"
  items={[
    { name: "Planner", role: "strategy", output: "Scoped the investor-safe narrative.", status: "done" },
    { name: "Builder", role: "interface", output: "Assembling the conversion surface.", status: "running" },
    { name: "Reviewer", role: "taste", output: "Waiting to reject generic cards.", status: "idle" },
  ]}
/>`,
      },
    ],
    props: [
      { name: "items", type: "AgentRunwayItem[]", desc: "Quick-form agent sequence." },
      { name: "title", type: "ReactNode", desc: "Optional section heading." },
      { name: "summary", type: "ReactNode", desc: "Optional supporting copy." },
      { name: "orientation", type: '"horizontal" | "vertical"', default: '"horizontal"', desc: "Track layout." },
      { name: "animated", type: "boolean", default: "true", desc: "Enable status pulse and entrance motion." },
    ],
    subprops: [
      { name: "AgentRunway.Item", props: [{ name: "status", type: '"idle" | "running" | "done" | "blocked"', desc: "Agent status." }] },
      { name: "AgentRunway.Status", props: [{ name: "status", type: '"idle" | "running" | "done" | "blocked"', desc: "Status tone." }] },
    ],
  },

  {
    slug: "prompt-composer",
    category: "Conversation",
    name: "PromptComposer",
    isNew: true,
    snark: "A textarea with enough ceremony to close a seed round.",
    sources: [
      { name: "chatgpt.com", url: "https://chatgpt.com" },
      { name: "claude.ai", url: "https://claude.ai" },
      { name: "perplexity.ai", url: "https://www.perplexity.ai" },
    ],
    extra: 1480,
    description:
      "A prompt panel with suggestions, model label, and submit CTA. It supports controlled and uncontrolled value handling for real demos.",
    examples: [
      {
        title: "Prompt panel",
        Demo: () => (
          <PromptComposer
            model="Synthetica Max"
            placeholder="Ask for the launch page to sound inevitable..."
            suggestions={[
              { label: "Make it enterprise" },
              { label: "Add urgency" },
              { label: "Remove obvious claims", value: "Rewrite this as proof, not promise." },
            ]}
            onSubmit={(value: string) => alert(value)}
          />
        ),
        code: `<PromptComposer
  model="Synthetica Max"
  placeholder="Ask for the launch page to sound inevitable..."
  suggestions={[
    { label: "Make it enterprise" },
    { label: "Add urgency" },
    { label: "Remove obvious claims", value: "Rewrite this as proof, not promise." },
  ]}
  onSubmit={(value) => runPrompt(value)}
/>`,
      },
    ],
    props: [
      { name: "placeholder", type: "string", desc: "Textarea placeholder." },
      { name: "defaultValue", type: "string", desc: "Initial uncontrolled value." },
      { name: "value", type: "string", desc: "Controlled value." },
      { name: "suggestions", type: "PromptComposerSuggestion[]", desc: "Suggestion chips." },
      { name: "model", type: "ReactNode", default: '"GPT-5"', desc: "Model label in the footer." },
      { name: "ctaLabel", type: "ReactNode", default: '"Generate"', desc: "Submit button label." },
      { name: "rows", type: "number", default: "4", desc: "Textarea row count." },
      { name: "onValueChange", type: "(value: string) => void", desc: "Change callback." },
      { name: "onSubmit", type: "(value: string) => void", desc: "Submit callback." },
    ],
    subprops: [
      { name: "PromptComposer.Field", props: [] },
      { name: "PromptComposer.Suggestion", props: [] },
      { name: "PromptComposer.Model", props: [] },
    ],
  },

  {
    slug: "fomo-feed",
    category: "Social Proof",
    name: "FomoFeed",
    isNew: true,
    snark: "Someone important is totally looking at this page.",
    sources: [
      { name: "producthunt.com", url: "https://www.producthunt.com" },
      { name: "stripe.com", url: "https://stripe.com" },
      { name: "vercel.com", url: "https://vercel.com" },
    ],
    extra: 2030,
    description:
      "A quiet activity feed or ticker for launch momentum, investor interest, and waitlist motion. It keeps urgency visible without turning the page into a slot machine.",
    examples: [
      {
        title: "Live feed",
        Demo: () => (
          <FomoFeed
            title="Live demand"
            caption="Activity from the last few very curated minutes."
            items={[
              { label: "Partner at Tier 1 joined the memo", meta: "seed list", time: "now", tone: "good" },
              { label: "24 teams are viewing pricing", meta: "enterprise", time: "2m", tone: "warn" },
              { label: "Design founder requested access", meta: "waitlist", time: "5m" },
            ]}
          />
        ),
        code: `<FomoFeed
  title="Live demand"
  items={[
    { label: "Partner at Tier 1 joined the memo", meta: "seed list", time: "now", tone: "good" },
    { label: "24 teams are viewing pricing", meta: "enterprise", time: "2m", tone: "warn" },
    { label: "Design founder requested access", meta: "waitlist", time: "5m" },
  ]}
/>`,
      },
      {
        title: "Ticker",
        Demo: () => (
          <FomoFeed
            variant="ticker"
            items={[
              { label: "Demo booked", meta: "Series A" },
              { label: "Procurement opened", meta: "enterprise", tone: "good" },
              { label: "Investor refreshed", meta: "again", tone: "warn" },
            ]}
          />
        ),
        code: `<FomoFeed
  variant="ticker"
  items={[
    { label: "Demo booked", meta: "Series A" },
    { label: "Procurement opened", meta: "enterprise", tone: "good" },
    { label: "Investor refreshed", meta: "again", tone: "warn" },
  ]}
/>`,
      },
    ],
    props: [
      { name: "items", type: "FomoFeedItem[]", desc: "Quick-form activity rows." },
      { name: "title", type: "ReactNode", desc: "Optional feed heading." },
      { name: "caption", type: "ReactNode", desc: "Optional supporting copy." },
      { name: "variant", type: '"feed" | "ticker"', default: '"feed"', desc: "Stacked feed or ticker treatment." },
      { name: "animated", type: "boolean", default: "true", desc: "Enable subtle motion." },
    ],
    subprops: [
      { name: "FomoFeed.Item", props: [{ name: "tone", type: '"neutral" | "good" | "warn" | "danger"', desc: "Item tone." }] },
      { name: "FomoFeed.Marker", props: [{ name: "tone", type: '"neutral" | "good" | "warn" | "danger"', desc: "Marker tone." }] },
    ],
  },

  /* ============================ ADDED COMPONENTS ============================ */
  {
    slug: "security-theater",
    category: "Surfaces",
    name: "SecurityTheater",
    isNew: true,
    snark: "Compliance, but make it investor-readable.",
    sources: [
      { name: "vercel.com", url: "https://vercel.com" },
      { name: "linear.app", url: "https://linear.app" },
      { name: "cursor.com", url: "https://cursor.com" },
    ],
    extra: 910,
    description:
      "A trust panel for security, compliance, and enterprise procurement claims. Pass `items` for the quick form, or compose Header, Seal, Grid, and Item manually.",
    examples: [
      {
        title: "Quick form",
        stretch: true,
        Demo: () => (
          <div style={{ padding: 24 }}>
            <SecurityTheater
              eyebrow="Trust posture"
              title="Enterprise-ready enough"
              summary="Every important box is either checked, in progress, or written in a way procurement can screenshot."
              seal="SOC 2-ish"
              items={[
                { label: "Encryption", value: "AES-256", status: "verified", detail: "At rest, in transit, and in the deck." },
                { label: "Data residency", value: "US/EU", status: "pending", detail: "Regional controls are rolling out." },
                { label: "Audit logs", value: "90 days", status: "verified" },
                { label: "Vendor review", value: "Soon", status: "attention" },
              ]}
            />
          </div>
        ),
        code: `<SecurityTheater
  eyebrow="Trust posture"
  title="Enterprise-ready enough"
  summary="Every important box is either checked, in progress, or written in a way procurement can screenshot."
  seal="SOC 2-ish"
  items={[
    { label: "Encryption", value: "AES-256", status: "verified" },
    { label: "Data residency", value: "US/EU", status: "pending" },
    { label: "Audit logs", value: "90 days", status: "verified" },
  ]}
/>`,
      },
      {
        title: "Compound layout",
        Demo: () => (
          <SecurityTheater animated={false}>
            <div className="pui-security__intro">
              <SecurityTheater.Header
                eyebrow="Manual composition"
                title="Bring your own procurement ritual"
                summary="Use the compound parts when the badge, copy, or grid needs custom placement."
              />
              <SecurityTheater.Seal>Reviewed</SecurityTheater.Seal>
            </div>
            <SecurityTheater.Grid>
              <SecurityTheater.Item label="Access review" value="Quarterly" status="verified" />
              <SecurityTheater.Item label="DPA" value="Available" status="verified" />
            </SecurityTheater.Grid>
          </SecurityTheater>
        ),
        code: `<SecurityTheater animated={false}>
  <div className="pui-security__intro">
    <SecurityTheater.Header
      eyebrow="Manual composition"
      title="Bring your own procurement ritual"
      summary="Use the compound parts when the badge, copy, or grid needs custom placement."
    />
    <SecurityTheater.Seal>Reviewed</SecurityTheater.Seal>
  </div>
  <SecurityTheater.Grid>
    <SecurityTheater.Item label="Access review" value="Quarterly" status="verified" />
    <SecurityTheater.Item label="DPA" value="Available" status="verified" />
  </SecurityTheater.Grid>
</SecurityTheater>`,
      },
    ],
    props: [
      { name: "title", type: "ReactNode", desc: "Panel heading." },
      { name: "eyebrow", type: "ReactNode", desc: "Small label above the heading." },
      { name: "summary", type: "ReactNode", desc: "Short supporting copy." },
      { name: "items", type: "SecurityTheaterItem[]", desc: "Quick-form trust rows." },
      { name: "seal", type: "ReactNode", desc: "Round proof badge content." },
      { name: "animated", type: "boolean", default: "true", desc: "Enable the scan sheen." },
    ],
    subprops: [
      { name: "SecurityTheater.Item", props: [
        { name: "label", type: "ReactNode", desc: "Claim label." },
        { name: "value", type: "ReactNode", desc: "Claim value." },
        { name: "status", type: '"verified" | "pending" | "attention"', desc: "Status tone." },
        { name: "detail", type: "ReactNode", desc: "Optional explanatory line." },
      ] },
    ],
  },

  {
    slug: "launch-timeline",
    category: "Surfaces",
    name: "LaunchTimeline",
    isNew: true,
    snark: "The day everything becomes generally available.",
    sources: [
      { name: "producthunt.com", url: "https://www.producthunt.com" },
      { name: "vercel.com/changelog", url: "https://vercel.com/changelog" },
      { name: "linear.app/changelog", url: "https://linear.app/changelog" },
    ],
    extra: 540,
    description:
      "An ordered launch sequence with done, active, and queued states. Use it for release days, public beta rollouts, and theatrical changelogs.",
    examples: [
      {
        title: "Release day",
        Demo: () => (
          <div style={{ width: "min(520px, 100%)" }}>
            <LaunchTimeline
              current={1}
              items={[
                { time: "09:00", title: "Waitlist opens", detail: "Synthetic demand warms up.", meta: "done" },
                { time: "10:30", title: "Launch tweet", detail: "All hands like it.", meta: "live" },
                { time: "12:00", title: "Founder podcast", detail: "Talk about distribution.", meta: "queued" },
              ]}
            />
          </div>
        ),
        code: `<LaunchTimeline
  current={1}
  items={[
    { time: "09:00", title: "Waitlist opens", detail: "Synthetic demand warms up." },
    { time: "10:30", title: "Launch tweet", detail: "All hands like it." },
    { time: "12:00", title: "Founder podcast", detail: "Talk about distribution." },
  ]}
/>`,
      },
    ],
    props: [
      { name: "items", type: "LaunchTimelineItem[]", desc: "Quick-form timeline steps." },
      { name: "current", type: "number", default: "0", desc: "Active step index when item state is omitted." },
      { name: "animated", type: "boolean", default: "true", desc: "Enable staged entrance." },
    ],
    subprops: [
      { name: "LaunchTimeline.Item", props: [{ name: "state", type: '"done" | "active" | "queued"', desc: "Step state." }] },
      { name: "LaunchTimeline.Time", props: [] },
      { name: "LaunchTimeline.Title", props: [] },
      { name: "LaunchTimeline.Detail", props: [] },
      { name: "LaunchTimeline.Meta", props: [] },
    ],
  },

  {
    slug: "metric-stack",
    category: "Social Proof",
    name: "MetricStack",
    isNew: true,
    snark: "The KPI grid went on a cleanse.",
    sources: [
      { name: "stripe.com", url: "https://stripe.com" },
      { name: "linear.app", url: "https://linear.app" },
      { name: "anthropic.com", url: "https://www.anthropic.com" },
    ],
    extra: 760,
    description:
      "A dense stack of proof metrics for traction, efficiency, and operational claims. It reads like a quiet financial terminal instead of a dashboard card mosaic.",
    examples: [
      {
        title: "Traction stack",
        Demo: () => (
          <MetricStack
            title="Board deck numbers"
            caption="Updated whenever the story needs to be true."
            metrics={[
              { label: "Pipeline", value: "$12.4M", delta: "+38%", tone: "good", caption: "Weighted enterprise opportunities." },
              { label: "CAC payback", value: "11d", delta: "-9d", tone: "good" },
              { label: "GPU burn", value: "$48k", delta: "+12%", tone: "warn" },
            ]}
          />
        ),
        code: `<MetricStack
  title="Board deck numbers"
  metrics={[
    { label: "Pipeline", value: "$12.4M", delta: "+38%", tone: "good" },
    { label: "CAC payback", value: "11d", delta: "-9d", tone: "good" },
    { label: "GPU burn", value: "$48k", delta: "+12%", tone: "warn" },
  ]}
/>`,
      },
    ],
    props: [
      { name: "metrics", type: "MetricStackMetric[]", desc: "Quick-form metric rows." },
      { name: "title", type: "ReactNode", desc: "Optional stack heading." },
      { name: "caption", type: "ReactNode", desc: "Optional supporting line." },
      { name: "density", type: '"comfortable" | "compact"', default: '"comfortable"', desc: "Spacing density." },
    ],
    subprops: [
      { name: "MetricStack.Row", props: [{ name: "tone", type: '"neutral" | "good" | "warn" | "danger"', desc: "Metric tone." }] },
      { name: "MetricStack.Label", props: [] },
      { name: "MetricStack.Value", props: [] },
      { name: "MetricStack.Delta", props: [{ name: "tone", type: '"neutral" | "good" | "warn" | "danger"', desc: "Delta tone." }] },
      { name: "MetricStack.Caption", props: [] },
    ],
  },

  {
    slug: "scroll-narrative",
    category: "Heroes",
    name: "ScrollNarrative",
    isNew: true,
    snark: "Because the workflow needs a dramatic pause.",
    sources: [
      { name: "framer.com", url: "https://www.framer.com" },
      { name: "runwayml.com", url: "https://runwayml.com" },
      { name: "openai.com", url: "https://openai.com" },
    ],
    extra: 680,
    description:
      "A stepped narrative section for explaining a workflow without adding another fake dashboard. It pairs concise copy with a sticky visual rail.",
    examples: [
      {
        title: "Workflow story",
        stretch: true,
        Demo: () => (
          <div style={{ padding: 28 }}>
            <ScrollNarrative
              title="From prompt to procurement"
              intro="A calm sequence for making impossible software feel inevitable."
              steps={[
                { kicker: "01", title: "Prompt", body: "Ask for the whole company to become autonomous.", visual: "Input intent" },
                { kicker: "02", title: "Polish", body: "Turn the output into something with margins and confidence.", visual: "Refine surface" },
                { kicker: "03", title: "Procure", body: "Hand security a panel that looks reassuring.", visual: "Approve spend" },
              ]}
            />
          </div>
        ),
        code: `<ScrollNarrative
  title="From prompt to procurement"
  intro="A calm sequence for making impossible software feel inevitable."
  steps={[
    { kicker: "01", title: "Prompt", body: "Ask for the whole company to become autonomous.", visual: "Input intent" },
    { kicker: "02", title: "Polish", body: "Turn the output into something with margins and confidence.", visual: "Refine surface" },
    { kicker: "03", title: "Procure", body: "Hand security a panel that looks reassuring.", visual: "Approve spend" },
  ]}
/>`,
      },
    ],
    props: [
      { name: "steps", type: "ScrollNarrativeStep[]", desc: "Quick-form story steps. Keep essential meaning in title/body; visual rail content is decorative." },
      { name: "title", type: "ReactNode", desc: "Optional section heading." },
      { name: "intro", type: "ReactNode", desc: "Optional intro copy." },
      { name: "align", type: '"left" | "right"', default: '"left"', desc: "Which side owns the text rail." },
    ],
    subprops: [
      { name: "ScrollNarrative.Stage", props: [] },
      { name: "ScrollNarrative.Step", props: [] },
      { name: "ScrollNarrative.Kicker", props: [] },
      { name: "ScrollNarrative.Title", props: [{ name: "as", type: '"h2" | "h3" | "h4"', default: '"h3"', desc: "Heading tag." }] },
      { name: "ScrollNarrative.Body", props: [] },
      { name: "ScrollNarrative.Visual", props: [] },
    ],
  },
];

export const CATEGORIES = Array.from(
  new Set(COMPONENTS.map((c) => c.category)),
);
